// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVlLzbWRGw_oftVrGQyXk-xDQ3zNt0Ldo',
    appId: '1:995783059687:web:37338036e29c2787d0da42',
    messagingSenderId: '995783059687',
    projectId: 'whatsapp-backend-ad480',
    authDomain: 'whatsapp-backend-ad480.firebaseapp.com',
    storageBucket: 'whatsapp-backend-ad480.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGL3gRK58IYMEn3p7U0OaW4cUy3TdFUkI',
    appId: '1:995783059687:android:9cb45fd4e6369311d0da42',
    messagingSenderId: '995783059687',
    projectId: 'whatsapp-backend-ad480',
    storageBucket: 'whatsapp-backend-ad480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5APhQkkCjI6NmAgjHt1oQ8EZtvXrC1Ao',
    appId: '1:995783059687:ios:df077cca4efc480dd0da42',
    messagingSenderId: '995783059687',
    projectId: 'whatsapp-backend-ad480',
    storageBucket: 'whatsapp-backend-ad480.appspot.com',
    iosClientId: '995783059687-h5khodq3c5vd64rqfrc89i9i09a39b5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5APhQkkCjI6NmAgjHt1oQ8EZtvXrC1Ao',
    appId: '1:995783059687:ios:92e34d76a895430ed0da42',
    messagingSenderId: '995783059687',
    projectId: 'whatsapp-backend-ad480',
    storageBucket: 'whatsapp-backend-ad480.appspot.com',
    iosClientId: '995783059687-ki323dlvrprddu5d21r2ndngrcci3bk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsapp.RunnerTests',
  );
}
